// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PolancoWatch.Infrastructure.Data;

#nullable disable

namespace PolancoWatch.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260521162444_AddUserGoogleDrive")]
    partial class AddUserGoogleDrive
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("PolancoWatch.Domain.Entities.AlertHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlertRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggeredAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlertRuleId");

                    b.ToTable("AlertHistories");
                });

            modelBuilder.Entity("PolancoWatch.Domain.Entities.AlertRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CooldownSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetricType")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Threshold")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("AlertRules");
                });

            modelBuilder.Entity("PolancoWatch.Domain.Entities.Backup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CloudFileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CloudLink")
                        .HasColumnType("TEXT");

                    b.Property<int>("CloudSyncStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.Property<int>("Format")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Backups");
                });

            modelBuilder.Entity("PolancoWatch.Domain.Entities.BackupSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CloudFolderId")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("CronExpression")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Format")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("KeepLocal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastRun")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NextRun")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetentionCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SendTelegram")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SyncToCloud")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseCron")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BackupSchedules");
                });

            modelBuilder.Entity("PolancoWatch.Domain.Entities.HistoricalMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CpuUsage")
                        .HasColumnType("REAL");

                    b.Property<double>("DiskUsage")
                        .HasColumnType("REAL");

                    b.Property<double>("MemoryUsage")
                        .HasColumnType("REAL");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HistoricalMetrics");
                });

            modelBuilder.Entity("PolancoWatch.Domain.Entities.NotificationSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EmailEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailMessageTemplate")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("FromEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SmtpEnableSsl")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SmtpHost")
                        .HasMaxLength(253)
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpPass")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SmtpUser")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("TelegramBotToken")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("TelegramChatId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TelegramEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TelegramMessageTemplate")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NotificationSettings");
                });

            modelBuilder.Entity("PolancoWatch.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleDriveFolderId")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleDriveRefreshToken")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastResetRequest")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResetToken")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResetTokenExpiry")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PolancoWatch.Domain.Entities.WebCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSlow")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUp")
                        .HasColumnType("INTEGER");

                    b.Property<double>("LatencyMs")
                        .HasColumnType("REAL");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WebMonitorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WebChecks");
                });

            modelBuilder.Entity("PolancoWatch.Domain.Entities.WebMonitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CheckIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastCheckTime")
                        .HasColumnType("TEXT");

                    b.Property<double>("LastLatencyMs")
                        .HasColumnType("REAL");

                    b.Property<bool>("LastStatusUp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Notify")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyOnSlow")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlowThresholdMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WebMonitors");
                });

            modelBuilder.Entity("PolancoWatch.Domain.Entities.WebMonitorDailyStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AverageLatencyMs")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("DownCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DownPercentage")
                        .HasColumnType("REAL");

                    b.Property<int>("SlowCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SlowPercentage")
                        .HasColumnType("REAL");

                    b.Property<int>("TotalChecks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UpCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("UpPercentage")
                        .HasColumnType("REAL");

                    b.Property<int>("WebMonitorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WebMonitorId");

                    b.ToTable("WebMonitorDailyStats");
                });

            modelBuilder.Entity("PolancoWatch.Domain.Entities.AlertHistory", b =>
                {
                    b.HasOne("PolancoWatch.Domain.Entities.AlertRule", "AlertRule")
                        .WithMany()
                        .HasForeignKey("AlertRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlertRule");
                });

            modelBuilder.Entity("PolancoWatch.Domain.Entities.WebMonitorDailyStats", b =>
                {
                    b.HasOne("PolancoWatch.Domain.Entities.WebMonitor", "WebMonitor")
                        .WithMany()
                        .HasForeignKey("WebMonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebMonitor");
                });
#pragma warning restore 612, 618
        }
    }
}
